# Sorties directes : build/Debug et build/Release (jamais build/x64/...)

set(GMEL_OUTPUT_ROOT "${CMAKE_BINARY_DIR}" CACHE PATH "Racine des binaires")

set(CMAKE_RUNTIME_OUTPUT_DIRECTORY "${GMEL_OUTPUT_ROOT}/$<CONFIG>")
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY "${GMEL_OUTPUT_ROOT}/$<CONFIG>")
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY "${GMEL_OUTPUT_ROOT}/$<CONFIG>")
set(CMAKE_PDB_OUTPUT_DIRECTORY "${GMEL_OUTPUT_ROOT}/$<CONFIG>")

if(NOT CMAKE_CONFIGURATION_TYPES AND CMAKE_BUILD_TYPE)
    set(CMAKE_RUNTIME_OUTPUT_DIRECTORY "${GMEL_OUTPUT_ROOT}/${CMAKE_BUILD_TYPE}")
    set(CMAKE_LIBRARY_OUTPUT_DIRECTORY "${GMEL_OUTPUT_ROOT}/${CMAKE_BUILD_TYPE}")
    set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY "${GMEL_OUTPUT_ROOT}/${CMAKE_BUILD_TYPE}")
    set(CMAKE_PDB_OUTPUT_DIRECTORY "${GMEL_OUTPUT_ROOT}/${CMAKE_BUILD_TYPE}")
endif()
