# Detecte Qt6 sur Windows / variables d'environnement / -DGMEL_QT_ROOT=
function(gmel_resolve_qt_prefix out_var)
    set(_candidates)

    if(DEFINED ENV{QT_DIR})
        list(APPEND _candidates "$ENV{QT_DIR}")
    endif()
    if(DEFINED ENV{Qt6_DIR})
        get_filename_component(_qt6_root "$ENV{Qt6_DIR}" DIRECTORY)
        get_filename_component(_qt6_root "${_qt6_root}" DIRECTORY)
        get_filename_component(_qt6_root "${_qt6_root}" DIRECTORY)
        list(APPEND _candidates "${_qt6_root}")
    endif()
    if(GMEL_QT_ROOT)
        list(APPEND _candidates "${GMEL_QT_ROOT}")
    endif()
    if(GAMEX_QT_ROOT)
        list(APPEND _candidates "${GAMEX_QT_ROOT}")
    endif()

    if(WIN32 AND EXISTS "C:/Qt")
        file(GLOB _qt_versions LIST_DIRECTORIES true "C:/Qt/6.*")
        list(SORT _qt_versions COMPARE NATURAL ORDER DESCENDING)
        foreach(_ver IN LISTS _qt_versions)
            foreach(_kit IN ITEMS msvc2022_64 msvc2019_64 mingw_64)
                list(APPEND _candidates "${_ver}/${_kit}")
            endforeach()
        endforeach()
    endif()

    foreach(_cand IN LISTS _candidates)
        if(EXISTS "${_cand}/lib/cmake/Qt6/Qt6Config.cmake")
            set(${out_var} "${_cand}" PARENT_SCOPE)
            return()
        endif()
    endforeach()

    set(${out_var} "" PARENT_SCOPE)
endfunction()
